### ISSUE TITLE
DC Voltage boundary condition for electrostatic simulations

### ISSUE THREAD

**Issue by archermarx** [osiris-code/osiris#4]
Hi all,

I am interested in using OSIRIS for a DC discharge simulation. Examining the [boundary conditions for the EMF solver](https://osiris-code.github.io/osiris/reference/emf_bound), it doesn't look I can specify an applied potential at a conducting surface. Is there a way to do this in some other manner?

Thanks,

Thomas

**Comment by jacobpierce1** [comment]
Hi Archer, 

It isn't possible to explicitly enforce a boundary condition on the value of the potential at the boundary because the code solves for the field rather than the potential. However, I can think of a workaround: you can apply a temporally constant external field consistent with the desired amount of charge on the wall. This would make it so that the total field is the self-consistent plasma field plus the field contributed by a fixed-charge conductor. 

If the interaction of self-consistent fields with the conductor interface is negligible, i.e. only the effect of the conductor fields on the plasma is important, then it seems to me that the external field used does not even need to correspond to a simulation boundary. You could, for example, put in the external field of a charged sphere somewhere inside the box. However, if the plasma or its fields would have a significant interaction with the conductor spatially, then it seems to me that this could only be handled by using a conducting wall boundary condition. In this case, specular boundary conditions should be safe for the particles. It seems to me that absorbing (=vpml) or thermal boundary conditions could also work, but I'm not 100% sure. 

Depending on your problem, it may be natural to initialize the plasma in equilibrium with the external fields so that the system starts off in a fluid or MHD equilibrium at t=0. It seems to me that the choice of equilibrium would be the same as what you would use if you were able to enforce the value of the potential through a boundary condition. 

Does that make sense? 

Jacob

**Comment by archermarx** [comment]
I think so. So if I want to impose an external voltage of V across a distance d, I would specify an external field of E = V / d across the electrodes. If I wanted to do an AC field instead, I suppose I could then just vary that field temporally with a provided frequency. I'll give that a shot soon and report back.

**Comment by jacobpierce1** [comment]
Yes, this sounds correct to me. You just need to make sure that the plasma initial condition is consistent with the desired voltage. Regardless of whether the plasma starts in equilibrium, the integral of the electric field (including both external and self-consistent) from one electrode to the other should equal the desired voltage at t=0.

**Comment by archermarx** [comment]
Great. Incidentally, is there any way to only solve for the plasma-induced electric fields (i.e. only use an applied external magnetic field)?

**Comment by jacobpierce1** [comment]
I'm not sure exactly what you mean by "solve for the plasma-induced electric fields". Are you asking whether it's possible to compute the electric fields for the specified plasma profile at t=0 within the simulation? Or by "solve" do you mean compute the numerical solution of the fields by time-evolving Maxwell's equations? 

I also don't understand why you would use an applied external magnetic field. Is there a magnetic field in the problem?

**Comment by archermarx** [comment]
Apologies, that could have been posed more clearly. I am solving a problem with an applied (either DC or AC) electric field and a transverse applied external magnetic field. I'm asking if I can avoid solving the plasma-induced magnetic fields and only solve for the electric field (basically assuming B = B_ext)

**Comment by jacobpierce1** [comment]
No worries. 

I don't see a simple way to evolve the simulation without time-evolving B other than manually setting B=0 in the code. If B_ext is much larger than the self-consistent B, which I think would be the approximation required for neglecting the self-consistent B, then it seems you would get approximately the same result as if you had actually neglected the self-consistent B. You wouldn't be able to capture electromagnetic waves, though. 

But I'm curious: why would you want to run the simulation without the self-consistent magnetic field?

**Comment by archermarx** [comment]
I was hoping that perhaps by not solving the self-consistent magnetic field we might be able to speed up the computation a little bit, as in my problem of interest the induced field is typically ~ 0.01 B0. It's not a huge deal though. Thanks for your help!

**Comment by jacobpierce1** [comment]
Ah, I see. Yes, I don't think this would result in a large speedup in this case. For most PIC simulations, the cost of the particle pushing routines dominates over the cost of the field solver. 

You're welcome! 🙂
